# Base URL of the site, the only required config argument
base_url = "https://cyejing.cn"

# Used in RSS by default
title = "Cyejing"
description = "Cyejing blog"
# The default language, used in RSS
default_language = "en"

# Theme name to use
# theme = "hermit_zola"

# Highlight all code blocks found
# Or enable the highlight.js in the 'extra' config section
highlight_code = true

# Which theme to use for the code highlighting.
# See below for list of accepted values
highlight_theme = "agola-dark"

# Whether to generate a RSS feed automatically
generate_feed = true
feed_filename = "rss.xml"

# The number of articles to include in the RSS feed. Will include all items if
# not set (the default).
# rss_limit = 20

# The taxonomies to be rendered for that site and their configuration
# Example:
# taxonomies = [
    # {name = "tags", rss = true}, # each tag will have its own RSS feed
    # {name = "categories", paginate_by = 5},  # 5 items per page for a term
    # {name = "authors"}, # Basic definition: no RSS or pagination
# ]

taxonomies = [
    {name = "tags", rss = true},
    # {name = "categories", paginate_by = 5},  # 5 items per page for a term
]

# Whether to compile the Sass files found in the `sass` directory
compile_sass = true

# Whether to build a search index out of the pages and section
# content for the `default_language`
build_search_index = true

# A list of glob patterns specifying asset files to ignore when
# processing the content directory.
# Defaults to none, which means all asset files are copied over to the public folder.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

# A list of directories to search for additional `.sublime-syntax` files in.
extra_syntaxes = []

# Optional translation object. The key if present should be a language code
[translations]

# Configuration of the Markdown rendering
[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

# You can put any kind of data in there and it
# will be accessible in all templates
[extra]

disable_comments = true

home_subtitle = "welcome to my blog"

# footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
footer_copyright = ''

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/tags", name = "Tags" },
]

hermit_social = [
    { name = "twitter", link = "https://twitter.com/cyejing" },
    { name = "github", link = "https://github.com/cyejing" },
    { name = "email", link = "mailto:jing23501@qq.com" }
]


# You can use highlight.js for code highlighting if you dont like the 
# default one
[extra.highlightjs]
enable = true
clipboard = true
theme = "railscasts"

[extra.disqus]
enable = false
# Take this from your Disqus account
shortname = "my-supa-dupa-blog"
# Cpmments can be disabled per page by setting:
# [extra]
# disable_comments = true
#
# in the posts front-matter


[extra.author]
name = "Cyejing"
email = "jing23501@qq.com"

[extra.google_analytics]
enable = true
id = "G-M5C0GNDPW2"

[extra.baidu_tongji]
enable = true
token = "51b9973e857f6178a51023ab6b40b6ee"

[extra.te_rum.enable]
enable = true
